#include <stdio.h>

/*
EJERCICIO 11:

CREA UN PROGRAMA QUE PERMITA A UNA TIENDA REGISTRAR LAS VENTAS DIARIAS DE UN
PRODUCTO DURANTE UNA SEMANA. UTILIZA UN ARRAY UNIDIMENSIONAL PARA ALMACENAR
LAS VENTAS DIARIAS. LUEGO, MUESTRA EL TOTAL DE VENTAS DE LA SEMANA
*/

int main(int argc, char const *argv[])
{
}
